### ISSUE TITLE
"Shannon" county was renamed to "Oglala Lakota" county in may 2015

### ISSUE THREAD

**Issue by raf18seb** [highcharts/map-collection-dist#75] opened 2020-11-10 08:37 UTC
Like in the title. Source: https://en.wikipedia.org/wiki/Oglala_Lakota_County,_South_Dakota
(in USA South Dakota state)

**Comment by wergeld** [comment] 2021-01-13 16:03
Also note that it has a new area code per the Census:
Shannon - 113
Oglala Lakota - 102

Why they felt the need to change the FIPS county code is just to maintain alphabetical ordering?

**Comment by KacperMadej** [comment] 2021-02-01 10:37
This issue is a duplicate of https://github.com/highcharts/map-collection-dist/issues/23

[The original issue in the main Highcharts repo](https://github.com/highcharts/highcharts/issues/8195) has a workaround: https://jsfiddle.net/vwLudjdq/

**Closed by KacperMadej** 2021-02-01 10:37 UTC
