### ISSUE TITLE
In newly contributed India map with Telangana, the hc-a2 code for Andhra Pradesh and Arunachal Pradesh is same. This will result in a conflict when try to plot data from Json

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#27] opened 2018-11-20 10:59 UTC
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#9236 for full details.

**Comment by KacperMadej** [comment] 2021-06-08 13:29
Duplicate of https://github.com/highcharts/map-collection-dist/issues/46#issuecomment-847008997
(link to a workaround)

**Closed by KacperMadej** 2021-06-08 13:29 UTC
Labels: enhancement
