### ISSUE TITLE
Ladakh is not included in India disputed map

### ISSUE THREAD

**Issue by Krishnamita** [highcharts/map-collection-dist#61] opened 2020-04-23 19:43 UTC
The disputed map of India contains Telengana state only,but doesn't contain the recently declared state,Ladakh,which is very important for plotting data statewise.

**Comment by KacperMadej** [comment] 2020-05-15 16:23
Hi @Krishnamita 

Thank you for reporting the problem.

The issue is a duplicate of already reported issue https://github.com/highcharts/map-collection-dist/issues/46
so this issue will be closed as a duplicate.

**Closed by KacperMadej** 2020-05-15 16:23 UTC
Labels: duplicate
