### ISSUE TITLE
Map of Norway: wrong data on municipality level, wrong boundary, wrong codes.

### ISSUE THREAD

**Issue by HuidongTian** [highcharts/map-collection-dist#91] opened 2021-10-27 11:14 UTC
The Geojson maps for Norway have several problems:
1. The map at the county level does not match the boundary of the map at the municipality level
2. There are several places that are wrong on the municipality level map. e.g. Orkland, Malvik. 
3. The code for the municipality level map are mismatched. 

 https://code.highcharts.com/mapdata/countries/no/no-all-all.geo.json

e.g.
"hc-group":"admin2","hc-key":"no-tf-3020","hc-a2":"NO","name":"Nordkapp"}
"hc-group":"admin2","hc-key":"no-vi-5435","hc-a2":"NF","name":"Norde Follo"

3020 is for Norde Follo, and 5435 is for Nordkapp.

**Comment by HuidongTian** [comment] 2021-11-16 12:33
Hi @KacperMadej  do you have a time table to fix this issue?

**Comment by KacperMadej** [comment] 2021-11-18 14:14
It's scheduled for the next 2 weeks so if everything goes well there should be a usable solution by that time.
https://github.com/highcharts/highcharts/projects/32#card-73059082

**Comment by KacperMadej** [comment] 2021-11-24 11:31
> If you check the municipalities: e.g. Orkland, Malvik, you will find that their boundaries are wrong, not due to the resolution.

@HuidongTian - I don't see what is wrong here - the boundaries seem ok to me. Below is a comparison between [norgeskart](https://www.norgeskart.no/#!?project=norgeskart&layers=1002&zoom=7&lat=7027429.25&lon=244735.50), [Highcharts Maps map](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all-all) (and this is the same on the [Trøndelag](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-td-all) map) and [Wikipedia](https://en.wikipedia.org/wiki/File:Norway_Tr%C3%B8ndelag_adm_location_map.svg).

![nor91](https://user-images.githubusercontent.com/8960408/143230234-55f6ee6c-2e55-4922-91c7-ca6fe08ec19f.jpg)

**Comment by HuidongTian** [comment] 2021-11-25 11:02
@KacperMadej
1. NorgeKart cannot be wrong. The map shown above is the boundary map including their ocean region, while the map from WiKipedia shows only their land boundary, but still, you can see the boundary of their ocean/sea area.
2. It's difficult to see the error if you focus only on one municipality. Check the gap between Orkland and Rindal, there is a gap. 
3. Zoom in the "Malvik" as much as possible, you will see two parts are in another municipality.

**Comment by KacperMadej** [comment] 2021-11-25 15:59
A lot is happening here, so lets go with a list and separate small issues for faster resolving of those:
- [x] "5435 is for Nordkapp" - done in https://github.com/highcharts/map-collection-dist/issues/60
- [ ] "3020 is for Norde Follo" - TODO (confirmed via [kartverket.no](https://www.kartverket.no/til-lands/fakta-om-norge/norske-fylke-og-kommunar))
- [ ] "the gap between Orkland and Rindal" - TODO
- [x] "Malvik" is like that also in other sources so this one is ok
![image](https://user-images.githubusercontent.com/8960408/143471829-832c6c6b-8f9a-457e-8637-0dd4a9905697.png)
[Source](https://www.norgeskart.no/#!?project=norgeskart&layers=1002&zoom=9&lat=7034064.86&lon=294129.25
)
<-- if you have comments for that @HuidongTian please let us know, but marking as done because "NorgeKart cannot be wrong." 😃 
- [ ] "The map at the county level does not match the boundary of the map at the municipality level" - TODO

**Comment by HuidongTian** [comment] 2021-11-25 16:48
@KacperMadej 
1. 5435 & 3020 is just an example of the mis-matching of municipality code and name. There could be more mismatched codes and names. You should go through all of them. 
2. Norgekart cannot be wrong. But the way of using their maps could be. For generating geojson format map, it's better don't choose such high resolution map because that will introduce redundant data, then make the size of  the generated geojson file unnecessarily high.   You can easily find the generated json file has a lot of repeated points. 
For example,  this one is much better. 
![Screenshot_20211125-174314](https://user-images.githubusercontent.com/60390550/143478276-f300f40b-3d31-4ab0-b708-7238acb0fac7.jpg)
Which will generate the simplified map like this one. 
![1920px-NO_5031_Malvik svg](https://user-images.githubusercontent.com/60390550/143478478-f2a974ef-4c88-49b5-97ab-c8c59322bbd9.png)

**Comment by raf18seb** [comment] 2021-11-29 10:08
Done in https://github.com/highcharts/map-collection/pull/14

**Comment by KacperMadej** [comment] 2021-11-29 11:21
@HuidongTian 

1. Will be taken care of in https://github.com/highcharts/map-collection-dist/issues/95
2. Simplification of geometry is done automatically in our map processing scripts so this could depend on the source - using a simplified source will prevent differences between the source and our maps. In the below demo a different map source is used. That demo could be used as a reference and as a workaround: https://jsfiddle.net/BlackLabel/fmunxt2e/1/

**Closed** 2022-01-24 14:22 UTC
Labels: bug
