### ISSUE TITLE
Western Sahara: questionable borders

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#9] opened 2018-11-20 10:39 UTC
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#6167 for full details.

**Comment by KacperMadej** [comment] 2021-08-16 12:28
Related to #87

**Comment by KacperMadej** [comment] 2023-08-08 12:39
Closing as a duplicate of #87

**Closed by KacperMadej** 2023-08-08 12:39 UTC
Labels: enhancement
