### ISSUE TITLE
world-continents: incorrect Asia data label placement

### ISSUE THREAD

**Issue by bm64** [highcharts/map-collection-dist#113] opened 2022-09-09 21:10 UTC
Asia data label has incorrect placement on world-continents map.
Demo: https://jsfiddle.net/BlackLabel/L6se3q9p/
JSON: https://code.highcharts.com/mapdata/custom/world-continents.topo.json

**Comment by alparius** [comment] 2023-02-03 15:17
bump

Any workaround?

**Comment by KacperMadej** [comment] 2023-02-06 12:09
Hi,

Thank you for reporting the problem - this is a duplicate of https://github.com/highcharts/highcharts/issues/18004

A proper solution will require changing the base of the placement logic - switching from bbox to lon/lat based options.

**Comment by hubertkozik** [comment] 2024-05-14 11:11
This issue is fixed.

**Closed by hubertkozik** 2024-05-14 11:11 UTC
Labels: bug
