### ISSUE TITLE
Adding state Ladakh to the map of india.

### ISSUE THREAD

**Issue by vdamodhar123** [highcharts/map-collection-dist#57] opened 2020-02-18 12:07 UTC
Hi,

"Ladakh" state is not added in India with a disputed territories map,

So please let us know when it will be added in India Map!

**Comment by KacperMadej** [comment] 2020-02-21 14:32
Hi @vdamodhar123 

Thank you for reporting about the problem.

More info: https://en.wikipedia.org/wiki/Jammu_and_Kashmir_Reorganisation_Act,_2019

Looks like a duplicate of https://github.com/highcharts/map-collection-dist/issues/46

Could you confirm that those are the same problems? @vdamodhar123

**Comment by vdamodhar123** [comment] 2020-03-02 06:27
yes these are the same problem

**Closed** 2020-03-03 11:13 UTC
Labels: Geopolitical change, duplicate, enhancement
