### ISSUE TITLE
Galesburg is not mapped correctly on Michigan

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#8] opened 2018-11-20 10:37 UTC
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#5714 for full details.

**Comment by KacperMadej** [comment] 2021-06-08 13:46
Duplicate of https://github.com/highcharts/map-collection-dist/issues/40

**Closed by KacperMadej** 2021-06-08 13:46 UTC
Labels: bug
