### ISSUE TITLE
Ladakh and jammu and kashmir union territory in India

### ISSUE THREAD

**Issue by VinitSawant09** [highcharts/map-collection-dist#65] opened 2020-06-14 10:28 UTC
Kindly add the new union territories of Ladakh and (Jammu and Kashmir) in India

**Comment by PrateekGoyal18** [comment] 2020-06-14 10:43
#46

**Comment by KacperMadej** [comment] 2020-10-29 11:33
Duplicate of https://github.com/highcharts/map-collection-dist/issues/46

**Closed by KacperMadej** 2020-10-29 11:33 UTC
