### ISSUE TITLE
Map for latest provinces and communes of Burundi

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#28] opened 2018-11-20 11:00 UTC
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#9419 for full details.

**Comment by pzisynergy** [comment] 2018-11-21 06:07
Hi,

Can the link below
https://data.humdata.org/dataset/burundi-administrative-level-0-1-and-2-administrative-boundaries
be helpful for commune level maps of Burundi for all 18 provinces. Please update the map for commune level
Thanks

**Comment by KacperMadej** [comment] 2018-11-21 10:15
@pzisynergy 

This took me longer than expected due to some issues with our map generation scripts, but here it is - a demo with a map of Burundi at communes level (admin 2):
http://jsfiddle.net/BlackLabel/kp5oczev/

To keep both maps at the same place I'm adding link for the first part of the issue (admin 1 map) here:
http://jsfiddle.net/BlackLabel/y8tgx5je/1/

**Comment by KacperMadej** [comment] 2018-11-21 10:30
and here's a heavier version of the admin 2 if you need all details from the source map:
http://jsfiddle.net/BlackLabel/kp5oczev/1/
(notice: the map file has ~0.5MB)

**Comment by pzisynergy** [comment] 2018-11-21 13:05
Thank you very much for all the effort you took.  
Just a query can these two be merged to show as drilldown the way its shown here https://www.highcharts.com/maps/demo/map-drilldown
When a province is drilled down then communes should be displayed. Can this be implemented at developer level at our end using highmaps or that merging is provided by Highmaps in the sample shown

**Comment by pzisynergy** [comment] 2018-11-22 05:59
@KacperMadej , Thank you so much. Its almost the way we want. If our developer comes across any problem in understanding we will surely get back to you for support/help. Thanks again.

**Comment by pzisynergy** [comment] 2019-01-08 12:12
Thanks for your ealier service for Burundi maps expansion on communes.
I would like to know if it is possible to provide link in the tool tip provided for hover on maps. We would like to display a link to separate page where user can navigate. So user should be able to click on that link shown in the tooltip.
Will it be possible? Please refer attached image for the same.
![tooltiprequired](https://user-images.githubusercontent.com/45089248/50830050-95ac3f00-136c-11e9-83f3-6eb36daa18f7.png)

**Comment by KacperMadej** [comment] 2019-01-08 21:30
@pzisynergy - This is a new problem, so please address the question to a support channel that we could resolve it as a part of technical support. https://www.highcharts.com/support
Issues in this repository are for bugs in map collection and is used as a bug tracker - this is not a bug and the problem is not about a map file.

P.S. Here's a related issue that with a workaround - https://github.com/highcharts/highcharts/issues/5722#issuecomment-249145442

**Comment by pzisynergy** [comment] 2019-01-09 07:05
Thanks for the workaround suggestion. Hope it helps.

**Comment by sharadambhore** [comment] 2019-01-17 07:06
Hello
please 
![map2](https://user-images.githubusercontent.com/46774395/51301159-3af1a200-1a54-11e9-953c-7350449ce1e3.png)
can possible  show number in Area  with respective Provence   .

I have to implements like this
![picturemessage_zxe1y0pm mcs](https://user-images.githubusercontent.com/46774395/51301226-73917b80-1a54-11e9-91e5-c34f365185d7.png)

**Closed** 2020-01-09 12:15 UTC
Labels: Geopolitical change
