### ISSUE TITLE
India map is incorrect in worldmap

### ISSUE THREAD

**Issue by shashivydyula** [highcharts/map-collection-dist#124] opened 2023-04-09 09:29 UTC
Although there is an option to plot correct India map with all it territories intact, the world map severely distorts it. Several parts of India is in Pakistan and China.

Kindly correct it so that appropriate map is projected.

This is the distorted map on world map plot:
![Distorted Map](https://user-images.githubusercontent.com/86909635/230765318-e9bf5e02-61ec-4938-a7a8-53bfcaee321c.png)

This is the correct India map that should appear on world map (ignore the states in below image. It is for depiction but the border should be like this):
![Actual Map](https://user-images.githubusercontent.com/86909635/230765346-27e6842c-5c17-4f5c-9d5c-32282e256804.png)

**Comment by shashivydyula** [comment] 2023-04-17 15:42
Any update on this please. It's been more than a week since any update.

**Comment by KacperMadej** [comment] 2023-08-08 13:05
The disputed map of India is available: https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/custom/in-all-disputed

The lack of world map with that version of India is already reported here:
https://github.com/highcharts/map-collection-dist/issues/88

Closing as duplicate of #88

**Closed by KacperMadej** 2023-08-08 13:05 UTC

**Comment by shashivydyula** [comment] 2023-08-08 16:20
Honestly, the so called disputed map is the actual map. Please don't call it as disputed map. The distorted map is the disputed map.
