### ISSUE TITLE
World map - support for India's disputed territories

### ISSUE THREAD

**Issue by zoltan-makranczi-anaplan** [highcharts/map-collection-dist#92] opened 2021-11-09 15:41 UTC
Hello HighCharts,

We're looking for version of the world map that contains India's disputed territories (preferable branched off from https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-highres3 ).

Our customers need this, and we saw this requested a couple of times ( https://github.com/highcharts/map-collection-dist/issues?q=is%3Aissue+is%3Aopen+India )

Is this something you could provide "officially" in the HC map collection, please?
Thank you!

**Comment by bmihestean** [comment] 2021-11-17 09:09
Hi Zolton, hi Highcharts, I'm also interested in this matter being clarified. Is there any update on having a refined map version for India?

Thanks!

**Comment by bmihestean** [comment] 2022-02-15 12:35
Hello Highcharts, do you have by any chance any updates on the matter?
Cheers

**Comment by KacperMadej** [comment] 2022-05-23 14:09
There are plans to resolve this. We do not have ETA for the fix right now.
Closing as a duplicate of https://github.com/highcharts/map-collection-dist/issues/88

**Closed by KacperMadej** 2022-05-23 14:09 UTC

**Comment by KacperMadej** [comment] 2022-05-23 14:10
(Change closed status as the initial duplicate reason was only partially mentioned and it looked at first glance as if this was closed as not planned)
